resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdp.yaml
  - db-migration-job.yaml

namespace: dummy

secretGenerator:
  - name: joinrpg-main
    envs:
      - joinrpg-main.secret.env