version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" 
    directory: "/src/JoinRpg.Portal" # Location of package manifests
    schedule:
      interval: "daily"
