resources:
  - ../base

namespace: prod

patchesJSON6902:
- target:
    kind: Ingress
    name: joinrpg-portal
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: joinrpg.ru
    - op: replace
      path: /spec/tls/0/hosts/0
      value: joinrpg.ru
    - op: add
      path: /spec/tls/0/hosts/1
      value: www.joinrpg.ru
    - op: replace
      path: /spec/tls/0/secretName
      value: joinrpg-ru-tls
    - op: add
      path: "/metadata/annotations/nginx.ingress.kubernetes.io~1from-to-www-redirect"
      value: true