apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: joinrpg-portal
  name: joinrpg-portal
  namespace: dummy
spec:
  endpoints:
  - path: /actuator/prometheus
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: joinrpg-portal