name: Deploy (dev/prod)
on:
  workflow_dispatch:
    inputs:
      deployVersion:
        description: Docker image to deploy
        required: true

jobs:
  deploy-dev:
    permissions: read-all
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: dev
      environment_url: https://bakery-staging.smolkov.spb.ru
    secrets: inherit

  deploy-prod:
    needs: deploy-dev
    permissions: read-all
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: prod
      environment_url: https://dev-joinrpg.ru
    secrets: inherit